<h1 align=center><font size = 5>Regression Models with Keras</font></h1>

<h2>Introduction</h2>

In this lab, we will  use the Keras library to build models for regression problems. 
The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. We will use the [concrete dataset]('https://cocl.us/concrete_data'). Ingredients include:

- Cement

- Blast Furnace Slag

- Fly Ash

- Water

- Superplasticizer

- Coarse Aggregate

- Fine Aggregate

Let's first load the dataset using Pandas library.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('concrete_data.csv')
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1030 non-null   float64
 1   Blast Furnace Slag  1030 non-null   float64
 2   Fly Ash             1030 non-null   float64
 3   Water               1030 non-null   float64
 4   Superplasticizer    1030 non-null   float64
 5   Coarse Aggregate    1030 non-null   float64
 6   Fine Aggregate      1030 non-null   float64
 7   Age                 1030 non-null   int64
 8   Strength            1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.5 KB

The data looks very clean and has no missing values. ready to be used to build our model.

Define the features and the label

In [4]:
X = data.drop('Strength', axis=1)
y = data[['Strength']]

The number of features

In [5]:
n_features = X.shape[1]
print('The number of features is '+str(n_features))

The number of features is 8

<h2>Import Keras and Packages</h2>

Let's start by importing the keras libraries and the packages that we would need to build a neural network.

In [6]:
import keras
from keras.models import Sequential
from keras.layers import Dense

import numpy as np

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>

1.  <a href="https://#item31">Part A. Build a baseline model</a>
2.  <a href="https://#item32">Part B. Normalize the data</a>
3.  <a href="https://#item33">Part C. Increate the number of epochs</a>
4.  <a href="https://#item34">Part D. Increase the number of hidden layers</a>

</font>
</div>

## Part A. Build a baseline model 

Use the Keras library to build a neural network with the following:

- One hidden layer of 10 nodes, and a ReLU activation function

- Use the adam optimizer and the mean squared error  as the loss function.

In [7]:
def one_hidden_layer(n_features=8):
  model = Sequential()
  model.add(Dense(10, activation='relu', input_shape=(n_features,)))
  model.add(Dense(1))

  model.compile(optimizer='adam', loss='mean_squared_error')

  return model

model = one_hidden_layer(n_features=8)

1. Split the data into a training and test sets by holding 30% of the data for testing

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

2. Train the model on the training data using 50 epochs and predict the result

In [9]:
model.fit(X_train, y_train,  epochs=50, verbose=0)

y_pred = model.predict(X_test)

10/10 [==============================] - 0s 4ms/step

3. Evaluate the model on the test data and compute the mean squared error between the predicted concrete strength and the actual concrete strength. 
We here use the `mean_squared_error` function from `Scikit-learn` library.

In [10]:
mse = mean_squared_error(y_test, y_pred)

print(f'The mean squared error is {mse}')

The mean squared error is 456.54489462428

4. Repeat steps 1 - 3, 50 times (i.e., create a list of 50 mean squared errors).
We create a function that combine the tree steps

In [11]:
def combine_steps(data, target, model=one_hidden_layer(n_features=8), iterations=50, epochs=50, verbose=0):
  MSE = []

  for i in range(iterations):
    X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=123)
    model.fit(X_train, y_train, epochs=epochs, verbose=verbose)
    y_pred = model.predict(X_test)
    MSE.append(mean_squared_error(y_test, y_pred))
    mean = np.mean(MSE)
    std = np.std(MSE)
    
    print(f'     The mean of MSE: {mean}')
    print(f'     The std  of MSE: {std}')
    print(f'             The MSE: {MSE[i]}')
    print(f'\n---------------------- Iteration {i+1} ----------------------\n')

  return MSE, mean, std

In [12]:
MSE_A, mean_A, std_A = combine_steps(X, y, model=one_hidden_layer(n_features=8), iterations=50, epochs=50, verbose=0)

10/10 [==============================] - 0s 6ms/step
     The mean of MSE: 172.75251294925647
     The std  of MSE: 0.0
             The MSE: 172.75251294925647

---------------------- Iteration 1 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 142.7935647833551
     The std  of MSE: 29.958948165901383
             The MSE: 112.8346166174537

---------------------- Iteration 2 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 130.83817548127558
     The std  of MSE: 29.735865833479025
             The MSE: 106.92739687711654

---------------------- Iteration 3 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 126.5726946850177
     The std  of MSE: 26.790842967695763
             The MSE: 113.77625229624401

---------------------- Iteration 4 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 122.32489498612904
     The std  of MSE: 25.423898651923952
             The MSE: 105.33369619057447

---------------------- Iteration 5 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 120.09377090459623
     The std  of MSE: 23.738894081697698
             The MSE: 108.93815049693215

---------------------- Iteration 6 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 119.12748645919778
     The std  of MSE: 22.10502912967987
             The MSE: 113.32977978680708

---------------------- Iteration 7 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 117.41468115322775
     The std  of MSE: 21.1681172482134
             The MSE: 105.42504401143759

---------------------- Iteration 8 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 116.0198137891071
     The std  of MSE: 20.343715000090263
             The MSE: 104.86087487614188

---------------------- Iteration 9 ----------------------

10/10 [==============================] - 0s 5ms/step
     The mean of MSE: 115.06202101314292
     The std  of MSE: 19.512467015208767
             The MSE: 106.44188602946537

---------------------- Iteration 10 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 114.47028122524488
     The std  of MSE: 18.698276166583533
             The MSE: 108.55288334626418

---------------------- Iteration 11 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 113.81311637668541
     The std  of MSE: 18.034427982473158
             The MSE: 106.58430304253143

---------------------- Iteration 12 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 113.22597312698612
     The std  of MSE: 17.445885815163177
             The MSE: 106.18025413059455

---------------------- Iteration 13 ----------------------

10/10 [==============================] - 0s 4ms/step
     The mean of MSE: 111.30060983133059
     The std  of MSE: 18.18819171423182
             The MSE: 86.2708869878088

---------------------- Iteration 14 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 108.26891415109823
     The std  of MSE: 20.914894176406783
             The MSE: 65.82517462784526

---------------------- Iteration 15 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 105.61012045306077
     The std  of MSE: 22.718516840685417
             The MSE: 65.72821498249884

---------------------- Iteration 16 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 102.7589382700902
     The std  of MSE: 24.816087471473562
             The MSE: 57.14002334256117

---------------------- Iteration 17 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 99.98153190243613
     The std  of MSE: 26.697616530916097
             The MSE: 52.76562365231681

---------------------- Iteration 18 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 97.61803052405848
     The std  of MSE: 27.8531757327655
             The MSE: 55.075005713260744

---------------------- Iteration 19 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 95.1193964203014
     The std  of MSE: 29.251148760091482
             The MSE: 47.64534844891705

---------------------- Iteration 20 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 92.75721524897482
     The std  of MSE: 30.438190319064454
             The MSE: 45.51359182244307

---------------------- Iteration 21 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 90.80762865307895
     The std  of MSE: 31.05139598335585
             The MSE: 49.86631013926589

---------------------- Iteration 22 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 88.77466255411113
     The std  of MSE: 31.83069035986388
             The MSE: 44.049408376819144

---------------------- Iteration 23 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 86.95366152817655
     The std  of MSE: 32.361172862314405
             The MSE: 45.07063793168128

---------------------- Iteration 24 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 85.2186120798062
     The std  of MSE: 32.826897611297
             The MSE: 43.57742531891775

---------------------- Iteration 25 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 83.76178867886705
     The std  of MSE: 33.003290945202004
             The MSE: 47.34120365538821

---------------------- Iteration 26 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 82.89343968495565
     The std  of MSE: 32.687621729064055
             The MSE: 60.316365843259206

---------------------- Iteration 27 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 81.53860396344017
     The std  of MSE: 32.86154664398739
             The MSE: 44.95803948252184

---------------------- Iteration 28 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 80.26852579761305
     The std  of MSE: 32.98197572541035
             The MSE: 44.70633715445424

---------------------- Iteration 29 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 79.06230762266956
     The std  of MSE: 33.07180478304536
             The MSE: 44.08198054930837

---------------------- Iteration 30 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 77.9575388648069
     The std  of MSE: 33.09195700741602
             The MSE: 44.81447612892738

---------------------- Iteration 31 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 76.93148206283314
     The std  of MSE: 33.068005872553
             The MSE: 45.12372120164634

---------------------- Iteration 32 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 76.03352985706746
     The std  of MSE: 32.9569270676066
             The MSE: 47.29905927256596

---------------------- Iteration 33 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 75.34954669959707
     The std  of MSE: 32.705529734907756
             The MSE: 52.778102503073974

---------------------- Iteration 34 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 74.58711684966157
     The std  of MSE: 32.54004262738374
             The MSE: 48.664501951854604

---------------------- Iteration 35 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 73.81113757436792
     The std  of MSE: 32.411676706637735
             The MSE: 46.65186293909004

---------------------- Iteration 36 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 73.11167981045365
     The std  of MSE: 32.244955004290944
             The MSE: 47.93120030954005

---------------------- Iteration 37 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 72.39166780299796
     The std  of MSE: 32.11786200463006
             The MSE: 45.75122352713745

---------------------- Iteration 38 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 71.77900607578458
     The std  of MSE: 31.927579701959353
             The MSE: 48.49786044167614

---------------------- Iteration 39 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 71.11485237368227
     The std  of MSE: 31.79762557872798
             The MSE: 45.21285799169146

---------------------- Iteration 40 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 70.47712816691019
     The std  of MSE: 31.665374968067162
             The MSE: 44.96815989602721

---------------------- Iteration 41 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 69.8934319749563
     The std  of MSE: 31.50858627861529
             The MSE: 45.96188810484622

---------------------- Iteration 42 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 69.48141593394888
     The std  of MSE: 31.254322091968255
             The MSE: 52.17674221163744

---------------------- Iteration 43 ----------------------

10/10 [==============================] - 0s 5ms/step
     The mean of MSE: 68.93989390142247
     The std  of MSE: 31.100506269185157
             The MSE: 45.65444650278664

---------------------- Iteration 44 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 68.49783340900188
     The std  of MSE: 30.89248458664433
             The MSE: 49.04717174249657

---------------------- Iteration 45 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 68.01361654093357
     The std  of MSE: 30.727022785517555
             The MSE: 46.22385747785922

---------------------- Iteration 46 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 67.67819407935619
     The std  of MSE: 30.483389105708923
             The MSE: 52.24876084679657

---------------------- Iteration 47 ----------------------

10/10 [==============================] - 0s 5ms/step
     The mean of MSE: 67.29458158758493
     The std  of MSE: 30.278612229214357
             The MSE: 49.26479447433609

---------------------- Iteration 48 ----------------------

10/10 [==============================] - 0s 5ms/step
     The mean of MSE: 66.84217957081151
     The std  of MSE: 30.13151694898662
             The MSE: 45.12688276568727

---------------------- Iteration 49 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 66.40765839188211
     The std  of MSE: 29.983358241966457
             The MSE: 45.11612062434147

---------------------- Iteration 50 ----------------------

## Part B. Normalize the data
Repeat Part A but use a normalized version of the data. Recall that one way to normalize the data is by subtracting the mean from the individual predictors and dividing by the standard deviation.

Let's normalize the data by substracting the mean and dividing by the standard deviation.

In [13]:

X_normalized = (X - X.mean()) / X.std()
X_normalized.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
count,1.030000e+03,1.030000e+03,1030.000000,1.030000e+03,1.030000e+03,1.030000e+03,1.030000e+03,1.030000e+03
mean,-4.139084e-16,-1.793603e-16,0.000000,-1.379695e-16,-1.931572e-16,7.243397e-16,-4.759946e-16,4.139084e-17
std,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.714421e+00,-8.564718e-01,-0.846733,-2.798851e+00,-1.038638e+00,-2.211064e+00,-2.239829e+00,-7.070160e-01
25%,-8.496407e-01,-8.564718e-01,-0.846733,-7.805147e-01,-1.038638e+00,-5.262618e-01,-5.317114e-01,-6.120340e-01
50%,-7.911350e-02,-6.014861e-01,-0.846733,1.607513e-01,3.269920e-02,-6.326279e-02,7.383152e-02,-2.795973e-01
75%,6.586406e-01,8.003558e-01,1.001791,4.885554e-01,6.688058e-01,7.264077e-01,6.288606e-01,1.636517e-01
max,2.476712e+00,3.309068e+00,2.279976,3.064159e+00,4.351528e+00,2.213149e+00,2.731735e+00,5.055221e+00

In [14]:
# Combaine the steps
MSE_B, mean_B, std_B = combine_steps(X_normalized, y, model=one_hidden_layer(n_features=8), iterations=50, epochs=50, verbose=0)

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 303.6399840120383
     The std  of MSE: 0.0
             The MSE: 303.6399840120383

---------------------- Iteration 1 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 232.39680889375865
     The std  of MSE: 71.24317511827968
             The MSE: 161.15363377547897

---------------------- Iteration 2 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 198.6046660497535
     The std  of MSE: 75.28309573382687
             The MSE: 131.02038036174318

---------------------- Iteration 3 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 175.1817630686272
     The std  of MSE: 76.78903261300516
             The MSE: 104.91305412524834

---------------------- Iteration 4 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 157.2343833456384
     The std  of MSE: 77.49631074701256
             The MSE: 85.44486445368325

---------------------- Iteration 5 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 143.3205397565595
     The std  of MSE: 77.28329077667031
             The MSE: 73.75132181116484

---------------------- Iteration 6 ----------------------

10/10 [==============================] - 0s 7ms/step
     The mean of MSE: 131.50441173475926
     The std  of MSE: 77.18282490257079
             The MSE: 60.60764360395783

---------------------- Iteration 7 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 121.52537950441513
     The std  of MSE: 76.87397148728571
             The MSE: 51.67215389200617

---------------------- Iteration 8 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 113.24639252289626
     The std  of MSE: 76.16637999181323
             The MSE: 47.014496670745295

---------------------- Iteration 9 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 106.3808394015515
     The std  of MSE: 75.13593064512888
             The MSE: 44.5908613094487

---------------------- Iteration 10 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 100.62310703811937
     The std  of MSE: 73.91687207795516
             The MSE: 43.04578340379819

---------------------- Iteration 11 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 95.7552792031197
     The std  of MSE: 72.588212122329
             The MSE: 42.209173018123224

---------------------- Iteration 12 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 91.57068211121691
     The std  of MSE: 71.2310841338885
             The MSE: 41.35551700838339

---------------------- Iteration 13 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 87.93364761139344
     The std  of MSE: 69.881417487559
             The MSE: 40.652199113688326

---------------------- Iteration 14 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 84.75491927455681
     The std  of MSE: 68.55152857389493
             The MSE: 40.25272255884397

---------------------- Iteration 15 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 81.9457937985529
     The std  of MSE: 67.26048509008055
             The MSE: 39.80891165849437

---------------------- Iteration 16 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 79.44226513932477
     The std  of MSE: 66.01620480038483
             The MSE: 39.38580659167481

---------------------- Iteration 17 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 77.20151369316193
     The std  of MSE: 64.81802902120724
             The MSE: 39.10873910839362

---------------------- Iteration 18 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 75.19599438896316
     The std  of MSE: 63.66042510973314
             The MSE: 39.09664691338527

---------------------- Iteration 19 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 73.37978170224781
     The std  of MSE: 62.55150822193397
             The MSE: 38.87174065465636

---------------------- Iteration 20 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 71.73417663768213
     The std  of MSE: 61.486038039136766
             The MSE: 38.822075346368315

---------------------- Iteration 21 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 70.23403322869508
     The std  of MSE: 60.46444827827313
             The MSE: 38.73102163996719

---------------------- Iteration 22 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 68.86179117691586
     The std  of MSE: 59.48463869551933
             The MSE: 38.672466037773

---------------------- Iteration 23 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 67.60516907292443
     The std  of MSE: 58.54320848986077
             The MSE: 38.70286068112117

---------------------- Iteration 24 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 66.44662241030728
     The std  of MSE: 57.640510916740546
             The MSE: 38.64150250749586

---------------------- Iteration 25 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 65.37209885120362
     The std  of MSE: 56.77594393076608
             The MSE: 38.50900987361181

---------------------- Iteration 26 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 64.37497275025304
     The std  of MSE: 55.94612947381618
             The MSE: 38.44969412553821

---------------------- Iteration 27 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 63.45379715880473
     The std  of MSE: 55.146133339149394
             The MSE: 38.58205618970066

---------------------- Iteration 28 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 62.597161557564704
     The std  of MSE: 54.376260718019886
             The MSE: 38.6113647228438

---------------------- Iteration 29 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 61.79707768073677
     The std  of MSE: 53.635644529613984
             The MSE: 38.59464525272682

---------------------- Iteration 30 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 61.04752704658884
     The std  of MSE: 52.922941316610775
             The MSE: 38.561008022150915

---------------------- Iteration 31 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 60.345095273624906
     The std  of MSE: 52.23607241353556
             The MSE: 38.569710311742696

---------------------- Iteration 32 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 59.684403936812544
     The std  of MSE: 51.57412733175814
             The MSE: 38.542281158816984

---------------------- Iteration 33 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 59.062219234442544
     The std  of MSE: 50.93557979246167
             The MSE: 38.53012405623257

---------------------- Iteration 34 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 58.47894673906617
     The std  of MSE: 50.317727042578504
             The MSE: 38.64768189626946

---------------------- Iteration 35 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 57.92653343266597
     The std  of MSE: 49.72146867427568
             The MSE: 38.59206770865883

---------------------- Iteration 36 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 57.40301678280814
     The std  of MSE: 49.145438025863804
             The MSE: 38.556417387926295

---------------------- Iteration 37 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 56.90643991920879
     The std  of MSE: 48.5884555433735
             The MSE: 38.53309596603309

---------------------- Iteration 38 ----------------------

10/10 [==============================] - 0s 8ms/step
     The mean of MSE: 56.43451396878548
     The std  of MSE: 48.049628926663075
             The MSE: 38.50132785269953

---------------------- Iteration 39 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 55.9853609874383
     The std  of MSE: 47.52804926162798
             The MSE: 38.468394714898444

---------------------- Iteration 40 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 55.555959257822714
     The std  of MSE: 47.02334953239571
             The MSE: 38.37989007319968

---------------------- Iteration 41 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 55.146408784538195
     The std  of MSE: 46.53412604626049
             The MSE: 38.35483937987273

---------------------- Iteration 42 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 54.75602375358367
     The std  of MSE: 46.05938545432439
             The MSE: 38.359852453493716

---------------------- Iteration 43 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 54.381958892759705
     The std  of MSE: 45.59899762019461
             The MSE: 38.297169877329

---------------------- Iteration 44 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 54.025966516118075
     The std  of MSE: 45.15128747457719
             The MSE: 38.36230194388646

---------------------- Iteration 45 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 53.6843775149732
     The std  of MSE: 44.71656587599507
             The MSE: 38.31287246345382

---------------------- Iteration 46 ----------------------

10/10 [==============================] - 0s 4ms/step
     The mean of MSE: 53.35751259471536
     The std  of MSE: 44.29381294719682
             The MSE: 38.321726262854675

---------------------- Iteration 47 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 53.04453188417633
     The std  of MSE: 43.88248001220649
             The MSE: 38.33443848884134

---------------------- Iteration 48 ----------------------

10/10 [==============================] - 0s 7ms/step
     The mean of MSE: 52.74347121307743
     The std  of MSE: 43.48244730598046
             The MSE: 38.29255900033025

---------------------- Iteration 49 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 52.45501670062594
     The std  of MSE: 43.09275871332616
             The MSE: 38.32074559050317

---------------------- Iteration 50 ----------------------

The mean of the MSE of the normalized data is less then the mean of the MSE of the unormalized data.

## Part C. Increate the number of epochs 

Repeat Part B but use 100 epochs this time for training.

In [15]:
# Combaine the steps
MSE_C, mean_C, std_C = combine_steps(X_normalized, y, model=one_hidden_layer(n_features=8), iterations=50, epochs=100, verbose=0)

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 165.28111827355883
     The std  of MSE: 0.0
             The MSE: 165.28111827355883

---------------------- Iteration 1 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 126.62737843034549
     The std  of MSE: 38.653739843213344
             The MSE: 87.97363858713214

---------------------- Iteration 2 ----------------------

10/10 [==============================] - 0s 4ms/step
     The mean of MSE: 103.71712089459737
     The std  of MSE: 45.23089876717559
             The MSE: 57.89660582310112

---------------------- Iteration 3 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 89.2384681782885
     The std  of MSE: 46.5109643622157
             The MSE: 45.8025100293619

---------------------- Iteration 4 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 79.71460409406816
     The std  of MSE: 45.75403581217123
             The MSE: 41.6191477571868

---------------------- Iteration 5 ----------------------

10/10 [==============================] - 0s 7ms/step
     The mean of MSE: 73.0057623117764
     The std  of MSE: 44.379829703935606
             The MSE: 39.46155340031756

---------------------- Iteration 6 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 67.9883671697581
     The std  of MSE: 42.886452032864305
             The MSE: 37.88399631764845

---------------------- Iteration 7 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 64.16366715627916
     The std  of MSE: 41.3731810273638
             The MSE: 37.390767061926454

---------------------- Iteration 8 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 61.17057963323167
     The std  of MSE: 39.915101732536925
             The MSE: 37.22587944885172

---------------------- Iteration 9 ----------------------

10/10 [==============================] - 0s 5ms/step
     The mean of MSE: 58.747934559136084
     The std  of MSE: 38.55796537788595
             The MSE: 36.94412889227574

---------------------- Iteration 10 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 56.75650911961606
     The std  of MSE: 37.29903998490498
             The MSE: 36.8422547244159

---------------------- Iteration 11 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 55.07034421438406
     The std  of MSE: 36.14634409512588
             The MSE: 36.522530256832106

---------------------- Iteration 12 ----------------------

10/10 [==============================] - 0s 4ms/step
     The mean of MSE: 53.61999758598014
     The std  of MSE: 35.089824440835386
             The MSE: 36.21583804513302

---------------------- Iteration 13 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 52.36513130617277
     The std  of MSE: 34.114762826533024
             The MSE: 36.051869668676986

---------------------- Iteration 14 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 51.26879389738915
     The std  of MSE: 33.21229621477267
             The MSE: 35.92007017441845

---------------------- Iteration 15 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 50.307819643676524
     The std  of MSE: 32.37232852083966
             The MSE: 35.89320583798715

---------------------- Iteration 16 ----------------------

10/10 [==============================] - 0s 4ms/step
     The mean of MSE: 49.45776234693981
     The std  of MSE: 31.58930287732627
             The MSE: 35.856845599152344

---------------------- Iteration 17 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 48.70088730522764
     The std  of MSE: 30.85748969436877
             The MSE: 35.8340115961207

---------------------- Iteration 18 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 48.003519041445095
     The std  of MSE: 30.17985242690768
             The MSE: 35.45089029335932

---------------------- Iteration 19 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 47.36716288990074
     The std  of MSE: 29.546173216932637
             The MSE: 35.27639601055807

---------------------- Iteration 20 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 46.78487518181003
     The std  of MSE: 28.951463327435775
             The MSE: 35.13912101999571

---------------------- Iteration 21 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 46.256934427735104
     The std  of MSE: 28.389099308449946
             The MSE: 35.17017859216167

---------------------- Iteration 22 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.77298487329792
     The std  of MSE: 27.857720761536566
             The MSE: 35.12609467567987

---------------------- Iteration 23 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.32739365820867
     The std  of MSE: 27.3547759264955
             The MSE: 35.07879571115609

---------------------- Iteration 24 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 44.91376501048262
     The std  of MSE: 26.8785889351822
             The MSE: 34.98667746505747

---------------------- Iteration 25 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 44.532172111026384
     The std  of MSE: 26.425593742152483
             The MSE: 34.9923496246204

---------------------- Iteration 26 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 44.181214489596606
     The std  of MSE: 25.993288549154464
             The MSE: 35.05631633242243

---------------------- Iteration 27 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 43.860699577957426
     The std  of MSE: 25.579178247214866
             The MSE: 35.206796963699716

---------------------- Iteration 28 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 43.55659149132458
     The std  of MSE: 25.18574941749373
             The MSE: 35.04156506560477

---------------------- Iteration 29 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 43.27321680643298
     The std  of MSE: 24.809406342739802
             The MSE: 35.0553509445765

---------------------- Iteration 30 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 43.00756818650426
     The std  of MSE: 24.449308083353294
             The MSE: 35.03810958864269

---------------------- Iteration 31 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 42.75883625103157
     The std  of MSE: 24.104072058416467
             The MSE: 35.04814625137811

---------------------- Iteration 32 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 42.52146948567011
     The std  of MSE: 23.773998695905043
             The MSE: 34.92573299410347

---------------------- Iteration 33 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 42.299213525158905
     The std  of MSE: 23.456545364347903
             The MSE: 34.96476682828917

---------------------- Iteration 34 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 42.08752030891893
     The std  of MSE: 23.151952941873017
             The MSE: 34.88995095675972

---------------------- Iteration 35 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 41.88616543593433
     The std  of MSE: 22.85919310859458
             The MSE: 34.838744881473225

---------------------- Iteration 36 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 41.695762966860336
     The std  of MSE: 22.577091160062935
             The MSE: 34.84127408019649

---------------------- Iteration 37 ----------------------

10/10 [==============================] - 0s 6ms/step
     The mean of MSE: 41.515174241358054
     The std  of MSE: 22.30510889723115
             The MSE: 34.833391397773774

---------------------- Iteration 38 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 41.347915528477486
     The std  of MSE: 22.041417428375556
             The MSE: 34.992084439015855

---------------------- Iteration 39 ----------------------

10/10 [==============================] - 0s 8ms/step
     The mean of MSE: 41.1909459705321
     The std  of MSE: 21.786220838831625
             The MSE: 35.06913321066211

---------------------- Iteration 40 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 41.03700976894075
     The std  of MSE: 21.540907627658896
             The MSE: 34.87956170528664

---------------------- Iteration 41 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 40.890264767265975
     The std  of MSE: 21.30365521444849
             The MSE: 34.873719698600375

---------------------- Iteration 42 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 40.74974208839798
     The std  of MSE: 21.074167407467773
             The MSE: 34.84778957594213

---------------------- Iteration 43 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 40.60832422252904
     The std  of MSE: 20.853940659144822
             The MSE: 34.527355990164665

---------------------- Iteration 44 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 40.475746886832546
     The std  of MSE: 20.639672138625453
             The MSE: 34.64234411618663

---------------------- Iteration 45 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 40.345579531339034
     The std  of MSE: 20.432761469422573
             The MSE: 34.48804853413111

---------------------- Iteration 46 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 40.219732743250454
     The std  of MSE: 20.232234964244583
             The MSE: 34.43078049117552

---------------------- Iteration 47 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 40.101379948783006
     The std  of MSE: 20.036808443922162
             The MSE: 34.53879860881316

---------------------- Iteration 48 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 39.98961704352055
     The std  of MSE: 19.846408173984475
             The MSE: 34.624997590922845

---------------------- Iteration 49 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 39.87899426439402
     The std  of MSE: 19.662196002075973
             The MSE: 34.45847808719364

---------------------- Iteration 50 ----------------------

The mean of the MSE using 100  epochs is less then the mean of the MSE using 50  epochs.

## Part D. Increase the number of hidden layers

Repeat part B but use a neural network with the following instead:

- Three hidden layers, each of 10 nodes and ReLU activation function.

In [16]:
def three_hidden_layer(n_features=8):
  model = Sequential()
  model.add(Dense(10, activation='relu', input_shape=(n_features,)))
  model.add(Dense(10, activation='relu'))
  model.add(Dense(10, activation='relu'))
  model.add(Dense(1))

  model.compile(optimizer='adam', loss='mean_squared_error')

  return model

In [17]:
# Combaine the steps
MSE_D, mean_D, std_D = combine_steps(X_normalized, y, model=three_hidden_layer(n_features=8), iterations=50, epochs=50, verbose=0)

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 129.14714614390184
     The std  of MSE: 0.0
             The MSE: 129.14714614390184

---------------------- Iteration 1 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 98.7501104411508
     The std  of MSE: 30.39703570275104
             The MSE: 68.35307473839976

---------------------- Iteration 2 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 81.0307321752871
     The std  of MSE: 35.26952298988094
             The MSE: 45.5919756435597

---------------------- Iteration 3 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 71.73040655269862
     The std  of MSE: 34.531762321214245
             The MSE: 43.8294296849332

---------------------- Iteration 4 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 66.1065619411916
     The std  of MSE: 32.87042135514195
             The MSE: 43.611183495163495

---------------------- Iteration 5 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 62.31523863915053
     The std  of MSE: 31.18104919054961
             The MSE: 43.358622128945186

---------------------- Iteration 6 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 59.54080109371599
     The std  of MSE: 29.6571892678139
             The MSE: 42.89417582110878

---------------------- Iteration 7 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 57.58924265289836
     The std  of MSE: 28.21817372357848
             The MSE: 43.92833356717497

---------------------- Iteration 8 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 55.8965253827451
     The std  of MSE: 27.031717240705404
             The MSE: 42.35478722151896

---------------------- Iteration 9 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 54.41638473973453
     The std  of MSE: 26.026135137417747
             The MSE: 41.09511895263946

---------------------- Iteration 10 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 53.09794995172893
     The std  of MSE: 25.16275536624404
             The MSE: 39.91360207167289

---------------------- Iteration 11 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 51.99890854085987
     The std  of MSE: 24.36570092850149
             The MSE: 39.909453021300294

---------------------- Iteration 12 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 51.10432009190766
     The std  of MSE: 23.614033613924033
             The MSE: 40.36925870448117

---------------------- Iteration 13 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 50.318534041057426
     The std  of MSE: 22.930751738934877
             The MSE: 40.10331538000436

---------------------- Iteration 14 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 49.67912527141976
     The std  of MSE: 22.282023255024985
             The MSE: 40.72740249649246

---------------------- Iteration 15 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 49.12924732655698
     The std  of MSE: 21.67933374506883
             The MSE: 40.88107815361509

---------------------- Iteration 16 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 48.63129143502367
     The std  of MSE: 21.12614956857906
             The MSE: 40.6639971704907

---------------------- Iteration 17 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 48.21341135760511
     The std  of MSE: 20.60309603943485
             The MSE: 41.10945004148955

---------------------- Iteration 18 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 47.81334052782398
     The std  of MSE: 20.125285975250986
             The MSE: 40.612065591763745

---------------------- Iteration 19 ----------------------

10/10 [==============================] - 0s 8ms/step
     The mean of MSE: 47.50037957456035
     The std  of MSE: 19.663080262599713
             The MSE: 41.55412146255122

---------------------- Iteration 20 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 47.29737670172074
     The std  of MSE: 19.21066516553568
             The MSE: 43.237319244928514

---------------------- Iteration 21 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 47.07013129521832
     The std  of MSE: 18.79784885842909
             The MSE: 42.297977758667486

---------------------- Iteration 22 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 46.85955444965892
     The std  of MSE: 18.411171038359523
             The MSE: 42.22686384735216

---------------------- Iteration 23 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 46.674298841877395
     The std  of MSE: 18.0454085555534
             The MSE: 42.41341986290248

---------------------- Iteration 24 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 46.488923307359116
     The std  of MSE: 17.704124865988625
             The MSE: 42.039910478920596

---------------------- Iteration 25 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 46.326281817175
     The std  of MSE: 17.37935877488112
             The MSE: 42.2602445625721

---------------------- Iteration 26 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 46.17171769176303
     The std  of MSE: 17.07268310339297
             The MSE: 42.15305043105182

---------------------- Iteration 27 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 46.00331859253483
     The std  of MSE: 16.787861864438515
             The MSE: 41.45654291337365

---------------------- Iteration 28 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.84137669819795
     The std  of MSE: 16.518119007950823
             The MSE: 41.30700365676511

---------------------- Iteration 29 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.68899976063259
     The std  of MSE: 16.261200967663825
             The MSE: 41.27006857123726

---------------------- Iteration 30 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.55087089746761
     The std  of MSE: 16.014654296534694
             The MSE: 41.407005002518126

---------------------- Iteration 31 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.3886322674961
     The std  of MSE: 15.788301168738858
             The MSE: 40.35923473837902

---------------------- Iteration 32 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.22163726532642
     The std  of MSE: 15.575917252726907
             The MSE: 39.87779719589659

---------------------- Iteration 33 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 45.074515152661824
     The std  of MSE: 15.368406418302765
             The MSE: 40.21948543473016

---------------------- Iteration 34 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 44.92508379021342
     The std  of MSE: 15.172307028337986
             The MSE: 39.844417466967805

---------------------- Iteration 35 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 44.77544186884601
     The std  of MSE: 14.986268091813873
             The MSE: 39.53797462098663

---------------------- Iteration 36 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 44.68118278224192
     The std  of MSE: 14.793178530544274
             The MSE: 41.287855664494494

---------------------- Iteration 37 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 44.53777259491284
     The std  of MSE: 14.623275716442086
             The MSE: 39.231595663736925

---------------------- Iteration 38 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 44.397900363646905
     The std  of MSE: 14.4603095394439
             The MSE: 39.082755575541334

---------------------- Iteration 39 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 44.26687189718089
     The std  of MSE: 14.301839325033404
             The MSE: 39.156761705006495

---------------------- Iteration 40 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 44.15368445129532
     The std  of MSE: 14.144476656837691
             The MSE: 39.62618661587252

---------------------- Iteration 41 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 44.02206106793398
     The std  of MSE: 14.000466127478832
             The MSE: 38.625502350119234

---------------------- Iteration 42 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 43.89593021937973
     The std  of MSE: 13.860836422888422
             The MSE: 38.59843458010102

---------------------- Iteration 43 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 43.77485276039301
     The std  of MSE: 13.725404499538863
             The MSE: 38.56852202396429

---------------------- Iteration 44 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 43.65986357471173
     The std  of MSE: 13.593459732233269
             The MSE: 38.600339404735195

---------------------- Iteration 45 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 43.57407343147374
     The std  of MSE: 13.457204092082373
             The MSE: 39.71351698576419

---------------------- Iteration 46 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 43.47146902465255
     The std  of MSE: 13.331447816147186
             The MSE: 38.75166631087769

---------------------- Iteration 47 ----------------------

10/10 [==============================] - 0s 3ms/step
     The mean of MSE: 43.37479530163685
     The std  of MSE: 13.208485818456033
             The MSE: 38.83113031989928

---------------------- Iteration 48 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 43.27418174127616
     The std  of MSE: 13.091581801968438
             The MSE: 38.44473084396293

---------------------- Iteration 49 ----------------------

10/10 [==============================] - 0s 2ms/step
     The mean of MSE: 43.179170681441576
     The std  of MSE: 12.977058671714953
             The MSE: 38.52362874954659

---------------------- Iteration 50 ----------------------

The mean of the MSE using three hidden layers is less then the mean of the MSE using one hidden layers.

<h2>Report the mean and the standard deviation of the mean squared errors</h2>

In [19]:
table = [ 
          ['A', mean_A, std_A],
          ['B', mean_B, std_B],
          ['C', mean_C, std_C],
          ['D', mean_D, std_D]
         ]

pd.DataFrame(table, columns = ['Part', 'mean MSE', 'std MSE']).set_index('Part')

       mean MSE    std MSE
Part
A     66.407658  29.983358
B     52.455017  43.092759
C     39.878994  19.662196
D     43.179171  12.977059